namespace HRMSAPPLICATION.DTO
{
    public class JobStatusDto
    {
        public int PnCompanyId { get; set; }
        public int BranchId { get; set; }
        public int PnJobStatusId { get; set; } // Generated by DB
        public string VJobStatusName { get; set; } // Part of Primary Key
        public string Status { get; set; } // Should be only 1 character

    }
}
