namespace HRMSAPPLICATION.DTO
{
    public class PaymCategoryDto
    {
        // Part of the Composite Key
        public int PnCompanyId { get; set; }

        // Part of the Composite Key
        public string BranchId { get; set; } = null!;

        // Part of the Composite Key (Identity)
        // Note: For new records, this will be 0 and auto-generated by SQL
        public int PnCategoryId { get; set; }

        // Mapped to v_CategoryName (MaxLength 40)
        public string VCategoryName { get; set; } = null!;

        // Mapped to status (MaxLength 1)
        public string? Status { get; set; }
    }
}
